name: Obsidian Release
on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        uses: ./.github/actions/setup
      - run: pnpm obsidian-version
      - name: Create releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for package in packages/*; do
            cd $package
            changed=$(git diff --quiet -- . || echo "true")

            if [ "$changed" = "true" ]; then
              echo "Changes detected in $package"
            else
              echo "No changes detected in $package"
            fi

            cd ../..
          done
