name: Obsidian Release
on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        uses: ./.github/actions/setup
      - run: pnpm obsidian-version
      - name: Create releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for package in packages/*; do
            cd $package
            changed=$(git diff --quiet -- . || echo "true")

            if [ "$changed" = "true" ]; then
              basename=$(basename $package)
              version=$(cat package.json | jq -r .version)
              tag="$basename@$version"
              echo "Releasing $basename@$version"
              pnpm build
              gh release create "$tag" --title "$tag" dist/*
            else
              echo "No changes detected in $package"
            fi

            cd ../..
          done
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: "release obsidian plugins"
