name: Obsidian Release
on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        uses: ./.github/actions/setup
      - run: pnpm obsidian-version
      - name: Create releases
        env:
          WRITE_TOKEN: ${{ secrets.WRITE_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          for package in packages/*; do
            cd $package
            changed=$(git diff --quiet -- . || echo "true")

            if [ "$changed" = "true" ]; then
              name=$(cat package.json | jq -r .name)
              version=$(cat package.json | jq -r .version)
              tag="$version"
              echo "Releasing $name@$version"
              pnpm build
              gh repo clone "tim-smart/$name" tmp/repo
              cp CHANGELOG.md dist/* tmp/repo/
              cd tmp/repo
              git add .
              git commit -m "Release $tag"
              git tag "$tag"
              git push --follow-tags "https://tim-smart:${WRITE_TOKEN}@github.com/tim-smart/$name.git" HEAD:main
              cd ../..
            else
              echo "No changes detected in $package"
            fi

            cd ../..
          done
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: "release obsidian plugins"
